version: 2.1
# orbs:
#   node: circleci/node@1.1.6
#   aws-cli: circleci/aws-cli@1.0.0

jobs:
  one:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "job 1"
      - run: mkdir -p my_folder_test

  two:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "job 2"
      - run: echo "ls"
      - run: ls
workflows:
  version: 2
  one_two:
    jobs:
      - one
      - two
  # build:
  #   executor:
  #     name: node/default
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #         steps:
  #           - run: yarn production
  # deploy:
  #   executor: aws-cli/default
  #   steps:
  #     - checkout
  #     - run: ls
# workflows:
# build-and-deploy:
#   jobs:
#     - build
#     - deploy:
#         requires:
#           - build
