version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn production
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run: echo "Run your code here"

workflows:
  build:
    jobs:
      - build
      - aws-cli-example
