version: "2.2"

services:
  web:
    image: boilerplate-front-next
    init: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
